"""empty message

Revision ID: 03dff65ae08f
Revises: bcbdd91ae82e
Create Date: 2022-07-28 14:27:11.539774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03dff65ae08f'
down_revision = 'bcbdd91ae82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('photo', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('photo', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    op.drop_column('group', 'photo')
    # ### end Alembic commands ###
