"""empty message

Revision ID: 6389d6fc0a76
Revises: 37c466638dd1
Create Date: 2022-07-31 11:51:07.356586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6389d6fc0a76'
down_revision = '37c466638dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('meeting', sa.Column('longitude', sa.Integer(), nullable=True))
    op.drop_column('meeting', 'iframe_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('iframe_map', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('meeting', 'longitude')
    op.drop_column('meeting', 'latitude')
    # ### end Alembic commands ###
