"""empty message

Revision ID: 81715d6a64de
Revises: 5e45b10d8eaf
Create Date: 2022-07-13 11:18:50.695311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81715d6a64de'
down_revision = '5e45b10d8eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.drop_column('group', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    op.drop_table('user_groups')
    # ### end Alembic commands ###
