"""empty message

Revision ID: 97b2240656c5
Revises: f8292e423b4b
Create Date: 2022-07-14 19:58:59.000783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b2240656c5'
down_revision = 'f8292e423b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('biketype', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('rutetype', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rutetype')
    op.drop_column('user', 'biketype')
    # ### end Alembic commands ###
