"""empty message

Revision ID: bd58544e59fc
Revises: e60158512e94
Create Date: 2022-07-31 12:49:09.435358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd58544e59fc'
down_revision = 'e60158512e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('aditional_info', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'aditional_info')
    # ### end Alembic commands ###
