"""empty message

Revision ID: d597b96a1c10
Revises: f00f1f7c5abe
Create Date: 2022-08-03 17:53:55.043879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd597b96a1c10'
down_revision = 'f00f1f7c5abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('cover', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('cover', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cover')
    op.drop_column('group', 'cover')
    # ### end Alembic commands ###
