"""empty message

Revision ID: f9db5713115b
Revises: e1bc786660da
Create Date: 2022-07-15 15:01:27.727674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9db5713115b'
down_revision = 'e1bc786660da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('routetype', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('bikemodel', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('routetype', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'routetype')
    op.drop_column('user', 'bikemodel')
    op.drop_column('group', 'routetype')
    # ### end Alembic commands ###
